version: '3'

networks:
  kafka-net:
    driver: bridge

services:
  kafka:
    image: apache/kafka:4.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "3000"
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_METADATA_LOG_DIR: /tmp/kraft-metadata-logs
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_GROUP_PROTOCOL_CONFIG_QUEUE_ENABLED: "true"
      KAFKA_GROUP_MAX_SIZE: "100"
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: "6000"
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_UNSTABLE_API_VERSIONS_ENABLE: "true"
      KAFKA_GROUP_COORDINATOR_REBALANCE_PROTOCOLS: classic,consumer,share
    networks:
      - kafka-net

  schema-registry:
    image: confluentinc/cp-schema-registry:7.9.0
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    networks:
      - kafka-net