/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.confluent.devrel;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    
    // Basic test to verify the app class can be instantiated
    @Test
    void appCanBeInstantiated() {
        assertDoesNotThrow(() -> new App());
    }
    
    // Basic sanity test for Kafka configuration constants
    @Test
    void kafkaConfigurationConstantsExist() {
        // This test verifies that static final fields exist in App class by reflection
        try {
            assertNotNull(App.class.getDeclaredField("BOOTSTRAP_SERVERS"));
            assertNotNull(App.class.getDeclaredField("SCHEMA_REGISTRY_URL"));
            assertNotNull(App.class.getDeclaredField("TOPIC"));
            assertNotNull(App.class.getDeclaredField("CONSUMER_GROUP"));
        } catch (NoSuchFieldException e) {
            fail("Required Kafka configuration constants not found in App class: " + e.getMessage());
        }
    }
}
